version: 2

sources:

  - name: fivetran_data # name of the source 
    schema: POSTGRES_RDS_FIVETRAN # this is the schema our raw data lives in
    database: FIVETRAN_DATABASE # this is the name of our database

    quoting:
      database: true
      schema: true
      identifier: true

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: users
        loaded_at_field: created_at
      - name: addresses 
      - name: CUSTOMER 
      - name: ORDERS_CSV  
      - name: events  
        loaded_at_field: created_at     
      - name: products 
      - name: order_items 
      - name: promos 